<br><br>
 <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Formulario de registro</h3>
              </div>
              <form action="" method="post">
                <input type="hidden" name="agregar" value="1">
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputPassword1">Nombre producto</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Igrese el nombre" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Codigo</label>
                    <input type="text" class="form-control" id="codigo" name="codigo" placeholder="Igrese el codigo" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Cantidad</label>
                    <input type="text" class="form-control" id="cantidad" name="cantidad" placeholder="Igrese la cantidad" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Precio compra</label>
                    <input type="text" class="form-control" id="precioC" name="precioC" placeholder="Igrese el precio de compra" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Precio venta</label>
                    <input type="text" class="form-control" id="precioV" name="precioV" placeholder="Igrese el precio de venta" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Fecha</label>
                    <input type="date" class="form-control" id="fecha" name="fecha" placeholder="Igrese la fecha" required>
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>