    <div class="modal fade" id="modalEditar">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title font-weight-normal">Actualizar Productos</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="formEdit" method="post" class="form" >
                <input type="hidden" name="editar" value="1">
                <div class="card-body">

                  <input type="hidden" class="form-control" id="id" name="id">

                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Nombre:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="nombre" name="nombre">
                    </div>
                  </div>

                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Codigo:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="codigo" name="codigo">
                    </div>
                  </div>

                 <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Cantidad:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="cantidad" name="cantidad">
                    </div>
                  </div>

                   <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Precio compra:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="precioC" name="precioC">
                    </div>
                  </div>

                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Precio venta:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="precioV" name="precioV">
                    </div>
                  </div>
                  
                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Fecha:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="date" class="form-control" id="fecha" name="fecha">
                    </div>
                  </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between table">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div><br>
    <div class="content">
      <div class="container-fluid">
      <a href="productos/agregarp"><button type="button" class="btn btn-success btn-sm">Agregar</button></a>
        <div class="row mr-7">
          <div class="col-lg-8"><br>
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Lista de productos registrados</h3>
              </div>
              <div class="card-body">
                <table class="table table-bordered" id="tablaProductos">
                  <thead>
                    <tr>
                      <th class="text-center">#</th>
                      <th class="text-center">Nombre</th>
                      <th class="text-center">Codigo</th>
                      <th class="text-center">Cantidad</th>
                      <th class="text-center">PrecioC</th>
                      <th class="text-center">PrecioV</th>
                      <th class="text-center">Fecha</th>
                      <th class="text-center">Accion</th> 
                    </tr>
                  </thead>
                  <tbody>
                      <?=$this->tabla ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    








