<?php if (Accesos::getDatos('validados')) {

  
?> 
<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0" >Bienvenido</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Starter Page</li>
            </ol>
          </div>
          
    </div>
  </div>
</div>

 <?php } else echo '<div class="btn-group" style="margin-left:520px;margin-top:250px"><a  href="'.BASE_URL.'login"><br><button type="button" class="btn btn-block btn-outline-warning btn-sm"style="margin-left:45px">Por Favor Ingresar al Sistema</button></a></div>';
?> 



