<br>
<div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-8">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Lista de productos registrados</h3>
              </div>
              <div class="card-body">
                <table class="table table-bordered  table-striped table-advance">
                  <thead>
                    <tr>
                      <th class="text-center">#</th>
                      <th class="text-center">Id producto</th>
                      <th class="text-center">Cantidad</th>
                      <th class="text-center">PrecioV</th>
                      <th class="text-center">PrecioC</th>
                      <th class="text-center">Total</th>
                      <th class="text-center">Fecha</th>
                      <th class="text-center">Accion</th> 
                    </tr>
                  </thead>
                  <tbody>
                      <?=$this->tabla ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    

